[mode]
normal_main = { bg = "#b994a8", fg = "#333333" }
normal_alt = { bg = "#333333", fg ="#b994a8" }

[indicator]
parent = { fg = "#333333", bg = "#b994a8"}
current = { fg = "#333333", bg = "#b994a8"}
