[ids]

*

[main]

shift = oneshot(shift)
meta = oneshot(meta)
control = oneshot(control)
leftalt = oneshot(alt)
rightalt = oneshot(alt)

capslock = backspace
backspace = delete
rightmeta = esc
esc = capslock